# Generated by Django 4.1.1 on 2022-09-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='video',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='LocalVideo',
            new_name='video',
        ),
    ]
