# Generated by Django 4.1.1 on 2022-09-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0004_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Details', models.CharField(max_length=2000)),
                ('Datecreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
