# Generated by Django 4.1.1 on 2022-09-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0005_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='Image',
            field=models.ImageField(default='/blank', upload_to='images/'),
        ),
    ]
